// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Action struct {
	ID          string
	Title       string
	Description sql.NullString
	Status      string
	CreatedAt   string
	UpdatedAt   string
	StartAt     string
	FinishAt    string
}
